# 初始化安装mysql
- name: mysql初始化
  shell: "{{ BASE_DIR }}/bin/mysqld --initialize-insecure --user={{ MYSQL_USER }} --basedir={{ BASE_DIR }} --datadir={{ DATA_DIR }}"

- name: 拷贝启动脚本到init.d下
  shell: "cp {{ BASE_DIR }}/support-files/mysql.server /etc/rc.d/init.d/mysqld"
  
- name: 修改启动脚本basedir参数
  lineinfile:
    dest: /etc/rc.d/init.d/mysqld
    regexp: "^basedir="
    insertbefore: "^# Default value, in seconds, afterwhich the script should timeout waiting"
    line: "basedir={{ BASE_DIR }}"

- name: 修改启动脚本datadir参数  
  lineinfile:
    dest: /etc/rc.d/init.d/mysqld
    regexp: "^datadir="
    insertbefore: "^# Default value, in seconds, afterwhich the script should timeout waiting"
    line: "datadir={{ DATA_DIR }}"
    
- name: 修改启动脚本权限属组
  file: dest=/etc/rc.d/init.d/mysqld state=file mode=0755 owner=root group=root    
    
- name: 配置环境变量PATH 
  shell: "if [ `grep {{ BASE_DIR }}/bin /etc/profile | wc -l`  -eq 0 ]; then echo 'export PATH=$PATH:{{ BASE_DIR}}/bin' >> /etc/profile && source /etc/profile; else source /etc/profile; fi" 

- name: 启动mysql并设置自启动
  shell: "systemctl daemon-reload && systemctl enable mysqld && systemctl start mysqld"   
  
- name: 设置数据库密码
  shell: "/bin/bash {{ SOURCE_DIR }}/change_passwd.sh"
  